"""DocuAgent entry point and back-compatible module surface.

The implementation is split across four modules; this one re-exports the flat API the
tests and `python docuagent.py` have always used:

- `core.py`      — schema constants, validation, normalization, cycle detection
- `workspace.py` — atomic persistence, UI state, migration, workspace inspection
- `scaffold.py`  — memory documents, the AI_ARCH.md tree, project scaffold
- `bootstrap.py` — Architecture Agent, deterministic interview, interview state
- `standards.py` — shared prompt safety rules and default project standards
- `memory.py`    — memory-sedimentation loop and reviewable candidates
- `main.py`      — HTTP routes and server

Runtime stays dependency-free.
"""

from __future__ import annotations

import sys as _sys
from types import ModuleType as _ModuleType
from typing import Any

from agents import (
    acquire_workspace_locks,
    agent_detail,
    append_error_memory,
    append_work_log,
    build_agent_context,
    clear_error_memory,
    clear_locks,
    list_agents,
    read_error_memory,
    read_registry,
    read_work_log,
    register_agent,
    release_workspace_locks,
    send_agent_message,
    update_agent_status,
)
from architecture_delta import (
    compare_architectures,
    format_delta,
    format_delta_summary,
)
from core import (
    APP_VERSION,
    BRIEF_MAX_CHARS,
    BUILD_ORDER_EDGE_TYPES,
    CONTRACTS_FILE,
    CONTRACTS_SCHEMA_VERSION,
    CONVERSATION_NODE_ID,
    DEFAULT_EDGE_TYPE,
    EDGE_TYPE_ALIASES,
    EDGE_TYPES,
    GROUP_KINDS,
    MANAGED_DIR,
    MAX_SCALE,
    MIN_SCALE,
    RESERVED_NODE_IDS,
    SCHEMA_VERSION,
    THINKING_MAX_CHARS,
    UI_STATE_VERSION,
    WINDOW_BAR_SLOTS,
    WorkspaceError,
    architecture_edge_reason_diagnostics,
    architecture_edge_reason_issues,
    architecture_graph_diagnostics,
    architecture_graph_quality_issues,
    architecture_readiness_diagnostics,
    architecture_readiness_issues,
    diagnostics_receipt,
    build_order_graph,
    clamp,
    coerce_float,
    edges_from_modules,
    ensure_acyclic_edges,
    ensure_acyclic_modules,
    find_edge_cycle,
    normalize_architecture,
    normalize_brief,
    normalize_contracts,
    normalize_edge_type,
    normalize_edges,
    normalize_flag,
    normalize_groups,
    normalized_list,
    normalized_text,
    optional_slug,
    simplify_architecture_edges,
    slugify,
    validate_module_path,
)
from workspace import (
    architecture_document,
    add_node_attachment,
    archive_node_attachment,
    atomic_write_json,
    atomic_write_text,
    contracts_path,
    default_ui_state,
    detect_mode,
    managed_path,
    migrate_architecture_shape,
    migrate_managed_directory,
    normalize_conversation_messages,
    normalize_node_id,
    normalize_ui_state,
    pop_architecture_history,
    prune_ui_state,
    push_architecture_history,
    read_conversation_history,
    read_stale_modules,
    read_architecture_history,
    read_contracts,
    read_json,
    read_node_attachments,
    read_ui_state,
    resolve_project_path,
    utc_now,
    visible_entries,
    write_conversation_history,
    write_contracts,
    write_node_attachments,
    resolve_node_attachment,
    write_stale_modules,
    write_ui_state,
)
from scaffold import (
    create_scaffold,
    minimal_contracts,
    render_initial_feature,
    render_project_overview,
    write_if_missing,
    write_initial_contracts,
)
from bootstrap import (
    INTERVIEW_TOPICS,
    ProviderConfig,
    ToolCallingNotSupported,
    apply_architecture_model_result,
    call_model_chat,
    openai_tool_schemas,
    model_error_message,
    normalize_question,
    normalize_thinking,
    refresh_progress,
    split_items,
    strip_json_fence,
    stream_architecture_model,
    stream_architecture_edit_model,
    uncovered_topics,
    validate_architecture_edit_result,
    validate_architecture_model_result,
)
from gitops import git_commit, git_diff, git_status
from contract_lint import (
    check_patch,
    check_working_files,
    contracts_with_delta,
    format_violations,
)
from microtask import dispatch_micro_task, generate_micro_task_patch
import main as _main
from main import (
    APP_ROOT,
    GLOBAL_CONFIG_PATH,
    MAX_BODY_BYTES,
    POST_ROUTES,
    STREAM_ROUTE_PATHS,
    WEB_NEXT_ROOT,
    WEB_ROOT,
    DocuAgentHandler,
    answer_bootstrap,
    choose_workspace,
    confirm_bootstrap,
    edit_architecture,
    fetch_provider_models,
    finalize_bootstrap,
    find_port,
    get_config,
    inspect_workspace,
    list_provider_models,
    main,
    provider_endpoint_parts,
    public_state,
    read_global_config,
    read_public_global_config,
    resolve_web_root,
    revise_bootstrap,
    run_server,
    save_config,
    save_conversation,
    save_global_config,
    save_ui_state,
    scan_import_route,
    start_bootstrap,
    start_onboard_route,
    accept_suggestion_route,
    reject_suggestion_route,
    terminal_exec,
    test_provider_connection,
    test_provider_reachable,
    undo_architecture,
    update_module_requirement,
    update_provenance,
    update_architecture_nodes,
    update_architecture_edges,
    reopen_architecture_review,
)
from tasks import (
    TASK_SCHEMA_VERSION,
    apply_hunks,
    apply_task_hunks,
    apply_task_partial,
    task_hunks,
    apply_task_patch,
    cancel_tasks,
    confirm_tasks,
    diagnose_file,
    diff_hunks,
    edit_task_patch,
    ensure_file_unchanged,
    generate_next_task,
    generate_wave,
    merge_planned_modules,
    normalize_task_plan,
    plan_tasks,
    read_apply_mode,
    read_task_state,
    reject_task,
    retry_documentation,
    retry_task,
    repair_task,
    resume_task,
    set_task_priority,
    sync_work_items_from_architecture,
    document_tree_gaps,
    generate_document_tree,
    maintain_document_tree,
    mark_stale_tasks,
    register_completed_documentation,
    stream_generate_wave,
    stream_generate_one_task,
    stream_plan_tasks,
    stream_verify_task,
    sync_docs,
    verify_task,
    write_apply_mode,
    write_task_state,
)
from debug import debug_file
from snapshots import (
    create_snapshot,
    list_snapshots,
    read_snapshots,
    restore_snapshot,
)
from memory import (
    apply_memory_candidate,
    read_memory_candidates,
    reject_memory_candidate,
    revert_memory_candidate,
    suggest_memory_updates,
)
from orchestrate import (
    normalize_orchestration,
    normalize_triage_result,
    orchestrate_tasks,
    stream_orchestrate_tasks,
    triage_errors,
    write_orchestration_record,
)
from importscan import (
    draft_contracts_from_scan,
    scan_project,
    read_scan,
    scan_summary,
    scan_prompt_text,
    write_contracts_draft,
)
from onboard import (
    accept_suggestion,
    build_onboard_state,
    call_onboard,
    execute_onboard_tool,
    normalize_doc_tree,
    normalize_suggestions,
    onboard_requires_loop,
    reject_suggestion,
    stream_onboard,
    stream_onboard_loop,
    validate_onboard_result,
    write_suggestion_attachments,
)

class _Forwarding(_ModuleType):
    """Make `patch("docuagent.X")` reach the function the HTTP routes actually call.

    The routes live in `main` and resolve these names in `main`'s namespace, so
    rebinding an attribute here would substitute a name nothing invokes. Setting this
    module's class lets attribute writes forward to `main` for those few names, which
    keeps the pre-split contract: patch `docuagent.X`, and the routes see it.
    """

    _FORWARDED = frozenset({
        "call_model_json",
        "call_architecture_model",
        "call_architecture_edit_model",
        "ask_directory",
    })

    def __getattribute__(self, name: str) -> Any:
        if name in _Forwarding._FORWARDED:
            return getattr(_main, name)
        return super().__getattribute__(name)

    def __setattr__(self, name: str, value: Any) -> None:
        if name in _Forwarding._FORWARDED:
            setattr(_main, name, value)
            return
        super().__setattr__(name, value)

    def __delattr__(self, name: str) -> None:
        if name in _Forwarding._FORWARDED:
            delattr(_main, name)
            return
        super().__delattr__(name)


_sys.modules[__name__].__class__ = _Forwarding

# Make the forwarded compatibility names real module globals so static analysis and
# star-import can resolve them. Writes to these names still forward to main, which is
# what lets the test suite patch `docuagent.call_model_json` and see the route use it.
call_model_json = _main.call_model_json
call_architecture_model = _main.call_architecture_model
call_architecture_edit_model = _main.call_architecture_edit_model
ask_directory = _main.ask_directory


__all__ = [
    "APP_VERSION",
    "APP_ROOT",
    "BRIEF_MAX_CHARS",
    "BUILD_ORDER_EDGE_TYPES",
    "DEFAULT_EDGE_TYPE",
    "CONVERSATION_NODE_ID",
    "DocuAgentHandler",
    "EDGE_TYPES",
    "EDGE_TYPE_ALIASES",
    "GLOBAL_CONFIG_PATH",
    "GROUP_KINDS",
    "MANAGED_DIR",
    "MAX_BODY_BYTES",
    "MAX_SCALE",
    "MIN_SCALE",
    "INTERVIEW_TOPICS",
    "ProviderConfig",
    "ToolCallingNotSupported",
    "call_model_chat",
    "openai_tool_schemas",
    "POST_ROUTES",
    "RESERVED_NODE_IDS",
    "SCHEMA_VERSION",
    "THINKING_MAX_CHARS",
    "UI_STATE_VERSION",
    "WEB_NEXT_ROOT",
    "WEB_ROOT",
    "WINDOW_BAR_SLOTS",
    "WorkspaceError",
    "answer_bootstrap",
    "apply_memory_candidate",
    "apply_architecture_model_result",
    "architecture_document",
    "add_node_attachment",
    "archive_node_attachment",
    "architecture_graph_quality_issues",
    "architecture_graph_diagnostics",
    "architecture_readiness_issues",
    "architecture_readiness_diagnostics",
    "architecture_edge_reason_diagnostics",
    "architecture_edge_reason_issues",
    "compare_architectures",
    "format_delta",
    "format_delta_summary",
    "diagnostics_receipt",
    "ask_directory",
    "atomic_write_json",
    "atomic_write_text",
    "build_order_graph",
    "call_architecture_edit_model",
    "call_architecture_model",
    "call_model_json",
    "choose_workspace",
    "clamp",
    "coerce_float",
    "confirm_bootstrap",
    "create_scaffold",
    "create_snapshot",
    "default_ui_state",
    "detect_mode",
    "edges_from_modules",
    "edit_architecture",
    "ensure_acyclic_edges",
    "ensure_acyclic_modules",
    "fetch_provider_models",
    "finalize_bootstrap",
    "find_edge_cycle",
    "find_port",
    "get_config",
    "inspect_workspace",
    "list_provider_models",
    "list_snapshots",
    "mark_stale_tasks",
    "register_completed_documentation",
    "main",
    "managed_path",
    "migrate_architecture_shape",
    "migrate_managed_directory",
    "model_error_message",
    "normalize_conversation_messages",
    "normalize_architecture",
    "normalize_brief",
    "normalize_edge_type",
    "normalize_edges",
    "normalize_flag",
    "normalize_groups",
    "normalize_node_id",
    "normalize_question",
    "normalize_thinking",
    "normalize_ui_state",
    "normalized_list",
    "normalized_text",
    "optional_slug",
    "provider_endpoint_parts",
    "prune_ui_state",
    "pop_architecture_history",
    "public_state",
    "push_architecture_history",
    "read_architecture_history",
    "read_conversation_history",
    "read_stale_modules",
    "read_snapshots",
    "read_global_config",
    "read_public_global_config",
    "read_json",
    "read_memory_candidates",
    "read_node_attachments",
    "read_ui_state",
    "refresh_progress",
    "reject_memory_candidate",
    "render_initial_feature",
    "render_project_overview",
    "resolve_project_path",
    "resolve_web_root",
    "restore_snapshot",
    "revise_bootstrap",
    "revert_memory_candidate",
    "run_server",
    "STREAM_ROUTE_PATHS",
    "save_config",
    "save_conversation",
    "save_global_config",
    "save_ui_state",
    "simplify_architecture_edges",
    "slugify",
    "split_items",
    "start_bootstrap",
    "suggest_memory_updates",
    "strip_json_fence",
    "stream_architecture_model",
    "stream_architecture_edit_model",
    "test_provider_connection",
    "test_provider_reachable",
    "TASK_SCHEMA_VERSION",
    "apply_task_patch",
    "apply_task_partial",
    "apply_task_hunks",
    "apply_hunks",
    "diff_hunks",
    "debug_file",
    "task_hunks",
    "edit_task_patch",
    "ensure_file_unchanged",
    "terminal_exec",
    "cancel_tasks",
    "confirm_tasks",
    "diagnose_file",
    "generate_next_task",
    "generate_wave",
    "merge_planned_modules",
    "normalize_task_plan",
    "normalize_orchestration",
    "normalize_triage_result",
    "git_status",
    "git_diff",
    "git_commit",
    "dispatch_micro_task",
    "generate_micro_task_patch",
    "orchestrate_tasks",
    "triage_errors",
    "plan_tasks",
    "read_apply_mode",
    "read_task_state",
    "reject_task",
    "retry_documentation",
    "retry_task",
    "repair_task",
    "resume_task",
    "set_task_priority",
    "sync_work_items_from_architecture",
    "stream_orchestrate_tasks",
    "stream_generate_wave",
    "stream_generate_one_task",
    "stream_plan_tasks",
    "stream_verify_task",
    "sync_docs",
    "document_tree_gaps",
    "generate_document_tree",
    "maintain_document_tree",
    "verify_task",
    "write_apply_mode",
    "write_task_state",
    "write_orchestration_record",
    "undo_architecture",
    "update_module_requirement",
    "update_provenance",
    "update_architecture_nodes",
    "update_architecture_edges",
    "reopen_architecture_review",
    "uncovered_topics",
    "acquire_workspace_locks",
    "agent_detail",
    "append_error_memory",
    "append_work_log",
    "build_agent_context",
    "clear_error_memory",
    "clear_locks",
    "list_agents",
    "read_error_memory",
    "read_registry",
    "read_work_log",
    "register_agent",
    "release_workspace_locks",
    "send_agent_message",
    "update_agent_status",
    "utc_now",
    "validate_architecture_edit_result",
    "validate_architecture_model_result",
    "validate_module_path",
    "visible_entries",
    "write_conversation_history",
    "write_node_attachments",
    "resolve_node_attachment",
    "write_stale_modules",
    "write_if_missing",
    "write_ui_state",
    "scan_project",
    "read_scan",
    "scan_summary",
    "scan_prompt_text",
    "accept_suggestion",
    "build_onboard_state",
    "call_onboard",
    "execute_onboard_tool",
    "normalize_doc_tree",
    "normalize_suggestions",
    "onboard_requires_loop",
    "reject_suggestion",
    "stream_onboard",
    "stream_onboard_loop",
    "validate_onboard_result",
    "write_suggestion_attachments",
    "scan_import_route",
    "start_onboard_route",
    "accept_suggestion_route",
    "reject_suggestion_route",
]


if __name__ == "__main__":
    main()
