"""Three-layer managed memory documents and the project scaffold.

Recovered from the pre-refactor `docuagent.py`; templates are byte-for-byte identical
to what that version emitted.

Business scaffold files generated here go through `write_if_missing`. Importing a
project must never overwrite existing business files. Formal AI_ARCH.md content is
generated by the Doc Maintainer model in task_docs.py.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from core import CONTRACTS_SCHEMA_VERSION
from workspace import atomic_write_text, utc_now, write_contracts


def bullets(values: list[str], empty: str = "To be refined") -> str:
    return "\n".join(f"- {value}" for value in values) if values else f"- {empty}"


def render_project_overview(state: dict[str, Any]) -> str:
    """`.docuagent/project.md` — long-term memory: the stable project overview."""
    answers = state["answers"]
    architecture = state["architecture"]

    return f"""# Project Purpose

{architecture.get("summary") or answers.get("goal") or "To be refined"}

# Users and Runtime

- Users: {answers.get("users") or "To be refined"}
- Platform: {answers.get("platform") or "To be refined"}
- Stack: {", ".join(architecture.get("stack", [])) or "To be refined"}

# Key Modules

{bullets([module.get("name", "Unnamed module") for module in architecture.get("modules", [])])}

# Data and Integrations

Data:

{bullets(architecture.get("data", []))}

Integrations:

{bullets(architecture.get("integrations", []))}

# Constraints and Invariants

{bullets(architecture.get("constraints", []))}

# Verification

{bullets(architecture.get("verification", []))}

# Memory Contract

- This document is long-term project memory and must remain concise.
- Current feature requirements live under `.docuagent/features/`.
- Working-set files are selected per edit transaction and are not persisted as memory.
"""


def render_initial_feature(state: dict[str, Any]) -> str:
    """`.docuagent/features/initial-build.md` — short-term memory: current feature."""
    architecture = state["architecture"]
    project_name = state["project"]["name"]
    verification = architecture.get("verification", [])
    constraints = architecture.get("constraints", [])

    return f"""# Goal

Create the first runnable project framework for {project_name}.

# Inputs and Outputs

- Input: confirmed architecture decisions from the initialization interview.
- Output: project scaffold, document tree, and architecture graph.

# Acceptance

{bullets(verification, "The generated project can run its minimum verification command.")}

# Constraints

{bullets(constraints, "Preserve the confirmed architecture boundaries.")}

# Verification

{bullets(verification, "Run the generated smoke test or minimum application entry point.")}

# Risks and Rollback

- Risk: the first scaffold may require framework-specific refinement.
- Rollback: generated business files are created only when absent; managed documents remain under `.docuagent/`.
"""


def write_if_missing(path: Path, content: str) -> bool:
    """Write only when absent. Returns True if the file was created.

    This is what makes importing an existing project safe.
    """
    if path.exists():
        return False
    atomic_write_text(path, content)
    return True


def minimal_contracts(state: dict[str, Any]) -> dict[str, Any]:
    """Build the initial Project Contract Registry for a fresh scaffold.

    The architecture is the source of truth for module ownership. Symbols the
    architecture model declared in `declared_exports` are pre-registered as
    `proposed` (先行接口): they tell every sub-agent which public symbols a
    module is expected to provide, before any code exists. They turn `active`
    once real production files reference them.
    """
    architecture = state.get("architecture", {})
    project = state.get("project", {})
    stack_text = " ".join(
        item for item in architecture.get("stack", []) if isinstance(item, str)
    )
    language = "Python" if ("python" in stack_text.lower() or not stack_text) else stack_text.strip()
    modules = []
    for module in architecture.get("modules", []):
        if not isinstance(module, dict) or not module.get("id"):
            continue
        exports = []
        for symbol in module.get("declared_exports", []):
            name = str(symbol).strip()
            if not name or name.startswith("_") or any(item["symbol"] == name for item in exports):
                continue
            exports.append({
                "symbol": name,
                "kind": "declared",
                "status": "proposed",
            })
        modules.append({
            "id": module["id"],
            "path": str(module.get("path") or ""),
            "depends_on": [
                dep for dep in module.get("depends_on", [])
                if isinstance(dep, str) and dep
            ],
            "exports": exports,
            "consumes": [],
        })
    return {
        "schema_version": CONTRACTS_SCHEMA_VERSION,
        "updated_at": utc_now(),
        "project": {
            "name": project.get("name") or "Untitled Project",
            "language": language,
            "runtime": "Python 3.12" if language == "Python" else "",
        },
        "vocabulary": [],
        "shared_kernel": [],
        "commands": [],
        "data_schema": [],
        "config_policy": [],
        "modules": modules,
        "recipes": [],
    }


def write_initial_contracts(project_root: Path, state: dict[str, Any]) -> None:
    """Create `.docuagent/contracts.json` for a newly initialized project."""
    write_contracts(project_root, minimal_contracts(state))


def _python_requirement(architecture: dict[str, Any]) -> str:
    """Return the confirmed Python major/minor requirement for the scaffold."""
    version_text = " ".join(
        [
            str(architecture.get("runtime") or ""),
            *[
                str(item)
                for item in architecture.get("stack", [])
                if isinstance(item, str)
            ],
        ]
    )
    match = re.search(r"\bpython\s*(\d+)\.(\d+)\b", version_text, re.IGNORECASE)
    if match:
        return f">={match.group(1)}.{match.group(2)}"
    return ">=3.12"


def _python_package_root(architecture: dict[str, Any], package: str) -> Path:
    """Choose the package root already promised by the confirmed architecture."""
    target_paths: list[str] = []
    module_paths: list[str] = []
    for module in architecture.get("modules", []):
        if not isinstance(module, dict):
            continue
        target_paths.extend(
            str(path).replace("\\", "/").strip("/")
            for path in module.get("target_files", [])
            if isinstance(path, str) and path.strip()
        )
        path = str(module.get("path") or "").replace("\\", "/").strip("/")
        if path:
            module_paths.append(path)

    paths = [*target_paths, *module_paths]
    root_prefix = f"{package}/"
    src_prefix = f"src/{package}/"
    if any(path == package or path.startswith(root_prefix) for path in paths):
        return Path(package)
    if any(path == f"src/{package}" or path.startswith(src_prefix) for path in paths):
        return Path("src") / package
    return Path("src") / package


def create_scaffold(project_root: Path, state: dict[str, Any]) -> list[str]:
    """Minimum runnable framework. Returns the relative paths actually created.

    Python gets a real runnable package; every other stack gets placeholder READMEs,
    because a wrong framework skeleton is worse than none — the real files come from
    the task DAG later.
    """
    # Importing an existing project generates no business files at all. This early
    # return, not per-file checks, is what guarantees nothing gets overwritten.
    if state["project"]["mode"] == "imported":
        return []

    architecture = state["architecture"]
    project = state["project"]
    slug = project["slug"]
    project_name = project["name"]
    summary = architecture.get("summary") or state["answers"].get("goal") or project_name

    # Only `stack` decides. A "python" token selects the runnable Python scaffold, as
    # does an unspecified stack — Python is the default. Any other named stack gets
    # placeholder READMEs, because a wrong framework skeleton is worse than none.
    stack_text = " ".join(architecture.get("stack", [])).lower()
    is_python = "python" in stack_text or not stack_text

    created: list[str] = []

    if is_python:
        package = slug.replace("-", "_")
        package_root = _python_package_root(architecture, package)
        python_requirement = _python_requirement(architecture)
        python_path = "." if package_root == Path(package) else "src"
        files = {
            Path("pyproject.toml"): f"""[project]
name = "{slug}"
version = "0.1.0"
requires-python = "{python_requirement}"

[tool.unittest]
start-directory = "tests"
""",
            package_root / "__init__.py": '"""Project package."""\n',
            package_root / "main.py": f'''def main() -> None:
    print("{project_name} is ready.")


if __name__ == "__main__":
    main()
''',
            Path("tests") / "test_smoke.py": f"""import unittest

from {package}.main import main


class SmokeTest(unittest.TestCase):
    def test_entry_point_is_callable(self) -> None:
        self.assertTrue(callable(main))


if __name__ == "__main__":
    unittest.main()
""",
            Path("README.md"): f"""# {project_name}

{summary}

## Run

```powershell
$env:PYTHONPATH = "{python_path}"
python -m {package}.main
```

## Verify

```powershell
$env:PYTHONPATH = "{python_path}"
python -m unittest discover -s tests -v
```
""",
        }
    else:
        files = {
            Path("README.md"): f"""# {project_name}

{summary}
""",
            Path("src")
            / "README.md": (
                "# Source\n\nFramework-specific source files will be generated from "
                "the task DAG.\n"
            ),
            Path("tests")
            / "README.md": (
                "# Tests\n\nVerification files will be generated with implementation "
                "tasks.\n"
            ),
        }

    for path, content in files.items():
        if write_if_missing(project_root / path, content):
            created.append(str(path))

    write_initial_contracts(project_root, state)
    return created
