import { describe, expect, it } from "vitest";
import type { BootstrapState } from "../api";
import { CONVERSATION_TAB } from "./workbenchConfig";
import { projectBootstrapTurn } from "./bootstrapProjection";

const base = { status: "interviewing", work_state: null, project: { name: "Demo", slug: "demo", root: "C:/demo", mode: "new" }, architecture: { summary: "", platform: "", language: "", runtime: "", frameworks: [], stack: [], modules: [{ id: "core", name: "Core", brief: "logic", responsibility: "", path: "src", depends_on: [], needs_ui: false, group: null }], groups: [], edges: [], data: [], integrations: [], constraints: [], verification: [], risks: [], unresolved: [] }, answers: {}, current_question: null, progress: 0, agent_mode: "", model_name: null, model_notice: null, thinking: "model reasoning" } as BootstrapState;

describe("bootstrap turn projection", () => {
  it("projects a question to one input tab and option chips", () => { const result = projectBootstrapTurn({ ...base, current_question: { id: "audience", title: "用户", prompt: "谁会使用？", placeholder: "目标用户", options: ["个人", "团队"] } }); expect(result.tabs).toEqual([{ id: "audience", label: "用户", promptKey: "audience", placeholder: "目标用户" }]); expect(result.activeTab).toBe("audience"); expect(result.message.chips?.map((chip) => chip.text)).toEqual(["个人", "团队"]); expect(result.thinkingFallback).toContain("问题类型：audience"); });
  it("projects regular and onboard review through the same confirmation gate", () => { const regular = projectBootstrapTurn({ ...base, status: "review" }); expect(regular.message.text).toContain("共 1 个模块"); expect(regular.message.chips?.map((chip) => chip.text)).toEqual(["开源选型", "全部确认", "确认架构", "修改架构"]); expect(regular.activeTab).toBe("revise"); const onboard = projectBootstrapTurn({ ...base, status: "review", onboard: true, onboard_summary: "扫描完成", suggestions: [{ module_id: "core", title: "Fix", detail: "", kind: "fix", files: [], priority: "high" }] }); expect(onboard.message.text).toContain("扫描完成"); expect(onboard.message.text).toContain("1 条"); });
  it("projects initialized projects to the shared conversation tab", () => { const regular = projectBootstrapTurn({ ...base, status: "initialized" }); expect(regular.tabs).toEqual([CONVERSATION_TAB]); expect(regular.message.text).toContain("Core（logic）"); expect(regular.refreshAttachments).toBe(false); const onboard = projectBootstrapTurn({ ...base, status: "initialized", onboard: true, suggestions: [{ module_id: "core", title: "Fix", detail: "", kind: "fix", files: [], priority: "high" }] }); expect(onboard.message.chips?.map((chip) => chip.text)).toContain("查看修改建议"); expect(onboard.refreshAttachments).toBe(true); });
  it("produces a safe fallback for an unexpected status", () => { const result = projectBootstrapTurn({ ...base, status: "paused" } as unknown as BootstrapState); expect(result.tabs).toEqual([]); expect(result.message.text).toBe("当前状态：paused。"); expect(result.thinkingFallback).toContain("paused"); });
  it("keeps the draft status out of the message text", () => { const result = projectBootstrapTurn({ ...base, provenance: [{ id: "p1", text: "推测", source: "inferred" }], topics_remaining: ["完成标准"], topics_total: 9, current_question: { id: "verify", title: "验收", prompt: "怎么算完成？", placeholder: "运行测试" } }); expect(result.message.text).toContain("怎么算完成？"); expect(result.message.text).not.toContain("当前草案"); expect(result.message.text).not.toContain("未覆盖主题"); expect(result.message.text).not.toContain("core"); });
  it("renders tradeoffs as a read-only view chip beside the option chips", () => { const result = projectBootstrapTurn({ ...base, current_question: { id: "auth", title: "登录", prompt: "登录态放哪？", placeholder: "方案", options: ["Cookie", "JWT"], tradeoffs: [{ option: "Cookie", pros: "实现简单", cons: "跨域麻烦" }, { option: "JWT", pros: "无状态", cons: "吊销困难" }] } }); const texts = result.message.chips?.map((chip) => chip.text); expect(texts).toEqual(["Cookie", "JWT", "权衡"]); const tradeoff = result.message.chips?.find((chip) => chip.text === "权衡")!; expect(tradeoff.type).toBe("view"); expect(tradeoff.detail).toContain("Cookie"); expect(tradeoff.detail).toContain("利：实现简单"); expect(tradeoff.detail).toContain("弊：吊销困难"); });
  it("omits the tradeoff chip when the question has none", () => { const result = projectBootstrapTurn({ ...base, current_question: { id: "users", title: "用户", prompt: "谁用？", placeholder: "描述", options: ["个人"] } }); expect(result.message.chips?.map((chip) => chip.text)).toEqual(["个人"]); });
  it("prepends the computed delta to the review message after a revision", () => { const result = projectBootstrapTurn({ ...base, status: "review", architecture_delta: { schema_version: 1, counts: { added: 1, removed: 0, changed: 0, moved: 0 }, changes: [{ kind: "added", subject: { type: "module", id: "auth" }, message: "新增模块 Auth。" }] } }); expect(result.message.text).toContain("较上一版：新增 1 · 移除 0 · 更新 0 · 仅位置调整 0"); expect(result.message.text).toContain("· 新增模块 Auth。"); });
  it("marks an unchanged revision instead of printing an empty delta", () => { const result = projectBootstrapTurn({ ...base, status: "review", architecture_delta: { schema_version: 1, counts: { added: 0, removed: 0, changed: 0, moved: 0 }, changes: [] } }); expect(result.message.text).toContain("（与上一版相同。）"); expect(result.message.text).not.toContain("较上一版"); });
  it("offers the per-claim ledger chip only when claims await a decision", () => { const withPending = projectBootstrapTurn({ ...base, status: "review", provenance: [{ id: "c1", text: "推测", source: "inferred" }] }); expect(withPending.message.chips?.map((chip) => chip.text)).toContain("确认推测"); const allConfirmed = projectBootstrapTurn({ ...base, status: "review", provenance: [{ id: "c1", text: "事实", source: "confirmed" }] }); expect(allConfirmed.message.chips?.map((chip) => chip.text)).not.toContain("确认推测"); });
});
